"""initial schema

Revision ID: 506b5252b57b
Revises: 
Create Date: 2026-08-20 02:03:19.050408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '506b5252b57b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courts',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('level', sa.Enum('SUPREME_COURT', 'HIGH_COURT', 'DISTRICT_COURT', 'TRIBUNAL', name='courtlevel'), nullable=False),
    sa.Column('jurisdiction_state', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courts_jurisdiction_state'), 'courts', ['jurisdiction_state'], unique=False)
    op.create_index(op.f('ix_courts_name'), 'courts', ['name'], unique=False)
    op.create_table('ingestion_dead_letters',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_document_id', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_dead_letters_source'), 'ingestion_dead_letters', ['source'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('documents_seen', sa.Integer(), nullable=False),
    sa.Column('documents_new', sa.Integer(), nullable=False),
    sa.Column('documents_updated', sa.Integer(), nullable=False),
    sa.Column('documents_unchanged', sa.Integer(), nullable=False),
    sa.Column('documents_failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_source'), 'ingestion_runs', ['source'], unique=False)
    op.create_table('ministries',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('source_value', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ministries_name'), 'ministries', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=True),
    sa.Column('role', sa.Enum('USER', 'RESEARCHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frequency', sa.Enum('IMMEDIATE', 'DAILY', 'WEEKLY', name='alertfrequency'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('citizen_profiles',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('derived_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('digilocker_linked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_profiles_user_id'), 'citizen_profiles', ['user_id'], unique=False)
    op.create_table('collections',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_table('departments',
    sa.Column('ministry_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('source_value', sa.String(length=500), nullable=False),
    sa.Column('normalized_value', sa.String(length=500), nullable=True),
    sa.Column('jurisdiction', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_ministry_id'), 'departments', ['ministry_id'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_index(op.f('ix_departments_state'), 'departments', ['state'], unique=False)
    op.create_table('judges',
    sa.Column('court_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('source_value', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judges_court_id'), 'judges', ['court_id'], unique=False)
    op.create_index(op.f('ix_judges_name'), 'judges', ['name'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('search_history',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_session_id'), 'search_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_document_id', sa.String(length=500), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('document_type', sa.Enum('ACT', 'RULE', 'REGULATION', 'GR', 'NOTIFICATION', 'CIRCULAR', 'ORDER', 'GAZETTE', 'JUDGMENT', 'SCHEME', 'ORDINANCE', 'STATUTE', 'GUIDELINE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_method', sa.Enum('STRUCTURAL', 'REGEX', 'NLP', 'LLM', 'MANUAL', 'UNKNOWN', name='extractionmethod'), nullable=True),
    sa.Column('jurisdiction', sa.Enum('CENTRAL', 'STATE', name='jurisdiction'), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('is_mixed_language', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_confidence', sa.Float(), nullable=True),
    sa.Column('date_extraction_method', sa.Enum('STRUCTURAL', 'REGEX', 'NLP', 'LLM', 'MANUAL', 'UNKNOWN', name='extractionmethod'), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('ministry_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('court_id', sa.UUID(), nullable=True),
    sa.Column('case_number', sa.String(length=200), nullable=True),
    sa.Column('act_number', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String(length=200)), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('text_available', sa.Boolean(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_document_id', name='uq_documents_source_natural_key')
    )
    op.create_index(op.f('ix_documents_act_number'), 'documents', ['act_number'], unique=False)
    op.create_index(op.f('ix_documents_case_number'), 'documents', ['case_number'], unique=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_court_id'), 'documents', ['court_id'], unique=False)
    op.create_index(op.f('ix_documents_date'), 'documents', ['date'], unique=False)
    op.create_index(op.f('ix_documents_department_id'), 'documents', ['department_id'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_jurisdiction'), 'documents', ['jurisdiction'], unique=False)
    op.create_index(op.f('ix_documents_ministry_id'), 'documents', ['ministry_id'], unique=False)
    op.create_index(op.f('ix_documents_source'), 'documents', ['source'], unique=False)
    op.create_index(op.f('ix_documents_source_document_id'), 'documents', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_documents_source_language'), 'documents', ['source_language'], unique=False)
    op.create_index(op.f('ix_documents_state'), 'documents', ['state'], unique=False)
    op.create_index('ix_documents_type_jurisdiction', 'documents', ['document_type', 'jurisdiction'], unique=False)
    op.create_index(op.f('ix_documents_year'), 'documents', ['year'], unique=False)
    op.create_index('ix_documents_year_state', 'documents', ['year', 'state'], unique=False)
    op.create_table('acts',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('act_number', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('short_title', sa.String(length=500), nullable=True),
    sa.Column('long_title', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acts_document_id'), 'acts', ['document_id'], unique=True)
    op.create_table('annotations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_document_id'), 'annotations', ['document_id'], unique=False)
    op.create_index(op.f('ix_annotations_user_id'), 'annotations', ['user_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_document_id'), 'bookmarks', ['document_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.create_table('circulars',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('circular_number', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circulars_document_id'), 'circulars', ['document_id'], unique=True)
    op.create_table('citations',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('cited_document_id', sa.UUID(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cited_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_cited_document_id'), 'citations', ['cited_document_id'], unique=False)
    op.create_index(op.f('ix_citations_document_id'), 'citations', ['document_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_document_id'), 'collection_items', ['document_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.Enum('CHAPTER', 'SECTION', 'CLAUSE', 'FACTS', 'ISSUES', 'ANALYSIS', 'DECISION', 'SUBJECT', 'PROVISIONS', 'ELIGIBILITY', 'CONDITIONS', 'GENERIC', name='chunktype'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section_ref', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunk_index')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_table('document_translations',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=200), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'language', name='uq_document_translation_lang')
    )
    op.create_index(op.f('ix_document_translations_document_id'), 'document_translations', ['document_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('diff_from_previous', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_document_version')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('document_views',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_views_document_id'), 'document_views', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_views_user_id'), 'document_views', ['user_id'], unique=False)
    op.create_table('gazettes',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('gazette_number', sa.String(length=200), nullable=True),
    sa.Column('part', sa.String(length=100), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gazettes_document_id'), 'gazettes', ['document_id'], unique=True)
    op.create_table('government_resolutions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('gr_number', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_government_resolutions_document_id'), 'government_resolutions', ['document_id'], unique=True)
    op.create_table('judgments',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=True),
    sa.Column('case_number', sa.String(length=200), nullable=True),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('citation', sa.String(length=300), nullable=True),
    sa.Column('petitioner', sa.Text(), nullable=True),
    sa.Column('respondent', sa.Text(), nullable=True),
    sa.Column('headnote', sa.Text(), nullable=True),
    sa.Column('judge_ids', sa.ARRAY(sa.String(length=36)), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_judgments_court_id'), 'judgments', ['court_id'], unique=False)
    op.create_index(op.f('ix_judgments_document_id'), 'judgments', ['document_id'], unique=True)
    op.create_table('legal_entities',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('canonical_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_entities_canonical_document_id'), 'legal_entities', ['canonical_document_id'], unique=False)
    op.create_index(op.f('ix_legal_entities_entity_type'), 'legal_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_legal_entities_name'), 'legal_entities', ['name'], unique=False)
    op.create_table('notifications',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('notification_number', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_document_id'), 'notifications', ['document_id'], unique=True)
    op.create_table('schemes',
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('eligibility_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('required_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('official_source', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemes_document_id'), 'schemes', ['document_id'], unique=True)
    op.create_index(op.f('ix_schemes_name'), 'schemes', ['name'], unique=False)
    op.create_table('change_radar_reports',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('changed_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_judgments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='impactlevel'), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_radar_reports_document_id'), 'change_radar_reports', ['document_id'], unique=False)
    op.create_index(op.f('ix_change_radar_reports_document_version_id'), 'change_radar_reports', ['document_version_id'], unique=False)
    op.create_table('legal_relationships',
    sa.Column('source_entity_id', sa.UUID(), nullable=False),
    sa.Column('target_entity_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('CONTAINS', 'AMENDS', 'AMENDED_BY', 'REPEALS', 'REPEALED_BY', 'IMPLEMENTS', 'IMPLEMENTED_BY', 'CITES', 'CITED_BY', 'INTERPRETS', 'INTERPRETED_BY', 'REFERS_TO', 'RELATED_TO', 'PUBLISHED_IN', 'ISSUED_BY', 'BELONGS_TO', 'SUPERSEDES', 'SUPERSEDED_BY', name='relationshiptype'), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['source_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['target_entity_id'], ['legal_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_relationships_relationship_type'), 'legal_relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_legal_relationships_source_document_id'), 'legal_relationships', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_legal_relationships_source_entity_id'), 'legal_relationships', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_legal_relationships_target_entity_id'), 'legal_relationships', ['target_entity_id'], unique=False)
    op.create_table('sections',
    sa.Column('act_id', sa.UUID(), nullable=False),
    sa.Column('parent_section_id', sa.UUID(), nullable=True),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ),
    sa.ForeignKeyConstraint(['parent_section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_act_id'), 'sections', ['act_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sections_act_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_legal_relationships_target_entity_id'), table_name='legal_relationships')
    op.drop_index(op.f('ix_legal_relationships_source_entity_id'), table_name='legal_relationships')
    op.drop_index(op.f('ix_legal_relationships_source_document_id'), table_name='legal_relationships')
    op.drop_index(op.f('ix_legal_relationships_relationship_type'), table_name='legal_relationships')
    op.drop_table('legal_relationships')
    op.drop_index(op.f('ix_change_radar_reports_document_version_id'), table_name='change_radar_reports')
    op.drop_index(op.f('ix_change_radar_reports_document_id'), table_name='change_radar_reports')
    op.drop_table('change_radar_reports')
    op.drop_index(op.f('ix_schemes_name'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_document_id'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_notifications_document_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_legal_entities_name'), table_name='legal_entities')
    op.drop_index(op.f('ix_legal_entities_entity_type'), table_name='legal_entities')
    op.drop_index(op.f('ix_legal_entities_canonical_document_id'), table_name='legal_entities')
    op.drop_table('legal_entities')
    op.drop_index(op.f('ix_judgments_document_id'), table_name='judgments')
    op.drop_index(op.f('ix_judgments_court_id'), table_name='judgments')
    op.drop_table('judgments')
    op.drop_index(op.f('ix_government_resolutions_document_id'), table_name='government_resolutions')
    op.drop_table('government_resolutions')
    op.drop_index(op.f('ix_gazettes_document_id'), table_name='gazettes')
    op.drop_table('gazettes')
    op.drop_index(op.f('ix_document_views_user_id'), table_name='document_views')
    op.drop_index(op.f('ix_document_views_document_id'), table_name='document_views')
    op.drop_table('document_views')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index(op.f('ix_document_translations_document_id'), table_name='document_translations')
    op.drop_table('document_translations')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_collection_items_document_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_citations_document_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_cited_document_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_circulars_document_id'), table_name='circulars')
    op.drop_table('circulars')
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_document_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_annotations_user_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_document_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_acts_document_id'), table_name='acts')
    op.drop_table('acts')
    op.drop_index('ix_documents_year_state', table_name='documents')
    op.drop_index(op.f('ix_documents_year'), table_name='documents')
    op.drop_index('ix_documents_type_jurisdiction', table_name='documents')
    op.drop_index(op.f('ix_documents_state'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_language'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_document_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_source'), table_name='documents')
    op.drop_index(op.f('ix_documents_ministry_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_jurisdiction'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_department_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_date'), table_name='documents')
    op.drop_index(op.f('ix_documents_court_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_number'), table_name='documents')
    op.drop_index(op.f('ix_documents_act_number'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_session_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_judges_name'), table_name='judges')
    op.drop_index(op.f('ix_judges_court_id'), table_name='judges')
    op.drop_table('judges')
    op.drop_index(op.f('ix_departments_state'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_ministry_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_citizen_profiles_user_id'), table_name='citizen_profiles')
    op.drop_table('citizen_profiles')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ministries_name'), table_name='ministries')
    op.drop_table('ministries')
    op.drop_index(op.f('ix_ingestion_runs_source'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_ingestion_dead_letters_source'), table_name='ingestion_dead_letters')
    op.drop_table('ingestion_dead_letters')
    op.drop_index(op.f('ix_courts_name'), table_name='courts')
    op.drop_index(op.f('ix_courts_jurisdiction_state'), table_name='courts')
    op.drop_table('courts')
    # ### end Alembic commands ###
